services:
    php:
        build:
            dockerfile: .docker/dev/Dockerfile
            context: .
            args:
                USER: ${USER}
        container_name: teamspeak-server-manager-dev
        networks:
            - teamspeak
        env_file:
            -  .env
        volumes:
            - .:/var/www/html
        ports:
            - "9501:9501"

networks:
    teamspeak:
        external: true
        name: teamspeak
