<?php

declare(strict_types=1);

use TeamspeakServerManager\DTO\ServerInfo;

/** @var $vars array<mixed> */

/** @var array<ServerInfo> $clients */
$infos = $vars['infos'];

var_dump($infos);

?>
<hgroup>
    <h1>Info</h1>
    <h2>Infos About The Servers</h2>
</hgroup>

<article>
    <figure>
        <p class="text-center mb-0">TODO: Put infos about teamspeak-server and teamspeak-server-manager here</p>
    </figure>
</article>
