<?php

declare(strict_types=1);

use TeamspeakServerManager\DTO\Client;

/** @var array<Client> $clients */

?>
<?php if ($clients === []): ?>
    <article hx-get="/" hx-trigger="every 3s" hx-swap="outerHTML">
        <p class="text-center mb-0">
            No one is currently online
        </p>
    </article>
<?php else: ?>
    <article hx-get="/" hx-trigger="every 3s" hx-swap="outerHTML">
        <figure>
            <table role="grid">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nickname</th>
                    <th scope="col">UUID</th>
                    <th scope="col">Connected</th>
                    <th scope="col">Online</th>
                    <th scope="col">Idle</th>
                </tr>
                </thead>
                <tbody>
                <?php $i = 1 ?>
                <?php foreach ($clients as $client): ?>
                    <tr>
                        <th scope="row"><?= $i ?></th>
                        <td><?= escape($client->nickname) ?></td>
                        <td title="<?= escape($client->uuid) ?>"><?= substr(escape($client->uuid), 0, 10) . '...' ?></td>
                        <td><?= $client->getLastConnectedReadable() ?></td>
                        <td><?= $client->getOnlineReadable() ?></td>
                        <td><?= $client->getIdleTimeReadable() ?></td>
                    </tr>
                    <?php $i = $i + 1 ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </figure>
    </article>
<?php endif; ?>
