<?php

declare(strict_types=1);

use TeamspeakServerManager\Helper\View;

/** @var array<array{uuid: string, nickname: string, time: int}> $times */

?>
<article hx-get="/time" hx-trigger="every 3s" hx-swap="outerHTML">
    <figure>
        <table role="grid">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nickname</th>
                <th scope="col">UUID</th>
                <th scope="col">Time</th>
            </tr>
            </thead>
            <tbody>
            <?php $i = 1 ?>
            <?php foreach ($times as $time): ?>
                <tr>
                    <th scope="row"><?= $i ?></th>
                    <td><?= View::escape($time['nickname']) ?></td>
                    <td title="<?= View::escape($time['uuid']) ?>"><?= substr(View::escape($time['uuid']), 0, 10) . '...' ?></td>
                    <td><?= View::secondsToHumanReadable($time['time']) ?></td>
                </tr>
                <?php $i = $i + 1 ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </figure>
</article>
